### ISSUE TITLE
Update _companies/madtree-brewing-company.html by Mike Stuart on 9/27/2016

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#65]
---

date: 2016-09-27T12:13:12.650Z
title: MadTree Brewing Company
industry: /companies/brewers-distilleries/
location: ''
image: 'http://i.imgur.com/V9wVXl9.jpg'
images: []
links: []
tags:
- craft beer
- brewing
- beer
- MadTree
- ''
  author: Mike Stuart
  authorEmail: mike.stuart@madtreebrewing.com
  created: 2016-09-27T12:13:12.651Z
  layout: company

---

<p>Cincinnati’s
MadTree Brewing made history when they opened in 2013 by becoming the first
modern craft brewery to can its beer in Ohio. They are currently constructing a
new $18M brewery in Cincinnati’s Oakley neighborhood set to open Winter 2016/2017.
MadTree is known for focusing more on great tasting beers rather than following
traditional brewing style guidelines. Their award-winning beers are distributed
throughout Cincinnati, Dayton, Columbus, Toledo, Athens and Northern Kentucky.
For more information about the beers, brewery, and taproom, visit <a target="_blank" rel="nofollow" href="http://madtreebrewing.com" title="Link: http://madtreebrewing.com">madtreebrewing.com</a> or connect with them on Facebook, Twitter, Instagram, and Snapchat.﻿</p>

**Comment by klcodanr** [comment]
Seems like a duplicate
