### ISSUE TITLE
Update _companies/uptown-identity-.html by Joi Meadows  on 9/27/2016

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#69]
---

date: 2016-09-28T01:54:49.357Z
title: 'Uptown Identity '
industry: /companies/retail/
location: ''
image: ''
images: []
links: []
tags: []
author: 'Joi Meadows '
authorEmail: contact@uptownidentity.com
created: 2016-09-28T01:54:49.370Z
layout: company

---

<div><b>Uptown Identity creates custom handbags that are intended to make you feel like royalty. Each purse is carefully crafted with ethnic printed fabrics of your choice, which encourages you to express your originality and embrace your heritage. Celebrate your Uptown Identity!</b></div><div><b>﻿<br></b></div><div></div>

**Comment by klcodanr** [comment]
Updating based on feedback:

---

date: 2016-09-28T01:54:49.357Z
title: 'Uptown Identity '
industry: /companies/retail/
location: ''
image: 'http://i.imgur.com/hRJzEmq.jpg'
images: []
links: 
- https://www.instagram.com/uptownidentity/
- https://www.facebook.com/uptownidentity/
- https://plus.google.com/107939047275168683243
  tags: []
  author: 'Joi Meadows '
  authorEmail: contact@uptownidentity.com
  created: 2016-09-28T01:54:49.370Z
  layout: company
  ---

<div>Uptown Identity creates custom handbags that are intended to make you feel like royalty. Each purse is carefully crafted with ethnic printed fabrics of your choice, which encourages you to express your originality and embrace your heritage. Celebrate your Uptown Identity!</div>
