### ISSUE TITLE
Update _companies/new-riff-distilling.html by Hannah Lowen on 9/29/2016

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#74]
---

date: 2016-09-29T14:55:18.045Z
title: New Riff Distilling
industry: /companies/brewers-distilleries/
location: 'Newport, KY'
image: ''
images: []
links:
- 'http://newriffdistilling.com'
  tags:
- bourbon
- whiskey
- craft whiskey
- distillery
- independent distillery
- event center
- events
- wedding venue
- cocktails
  author: Hannah Lowen
  authorEmail: hannah@newriffdistilling.com
  created: 2016-09-29T14:55:18.046Z
  layout: company

---

<div><div>Knowledge, Ambition and Absolute Drive for Quality—these are the hallmarks of New Riff.<br><br>Craft Distillery and Event Center in Newport, Kentucky. Specializing in Kentucky Bourbon and Rye Whiskey.﻿<br><br>Everything you see, taste, learn and experience reflects our dedication to delivering only the best, and proves we don’t hold anything back. This is our passion and vision brought to life. This is a landmark that inspires people to cross borders, connect on a different level, and amplify their expectations of the world of spirits. We’re creating our own sound, setting our own standard and influencing generations to come.</div></div>

**Comment by klcodanr** [comment]
Adding Logo: 

---

date: 2016-09-29T14:55:18.045Z
title: New Riff Distilling
industry: /companies/brewers-distilleries/
location: 'Newport, KY'
image: 'http://i.imgur.com/fLSX6OW.jpg'
images: []
links:
- 'http://newriffdistilling.com'
  tags:
- bourbon
- whiskey
- craft whiskey
- distillery
- independent distillery
- event center
- events
- wedding venue
- cocktails
  author: Hannah Lowen
  authorEmail: hannah@newriffdistilling.com
  created: 2016-09-29T14:55:18.046Z
  layout: company

---

<div><div>Knowledge, Ambition and Absolute Drive for Quality—these are the hallmarks of New Riff.<br><br>Craft Distillery and Event Center in Newport, Kentucky. Specializing in Kentucky Bourbon and Rye Whiskey.﻿<br><br>Everything you see, taste, learn and experience reflects our dedication to delivering only the best, and proves we don’t hold anything back. This is our passion and vision brought to life. This is a landmark that inspires people to cross borders, connect on a different level, and amplify their expectations of the world of spirits. We’re creating our own sound, setting our own standard and influencing generations to come.</div></div>
