### ISSUE TITLE
Update _companies/christian-moerlein-brewing-co-.html by Ali Daniels on 10/10/2016

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#87]
---

date: 2016-10-10T20:55:37.830Z
title: Christian Moerlein Brewing Co.
industry: /companies/brewers-distilleries/
location: ''
image: 'http://i.imgur.com/ky2JmYE.jpg'
images: []
links: []
tags: []
author: Ali Daniels
authorEmail: adaniels@christianmoerlein.com
created: 2016-10-10T20:55:37.837Z
layout: company

---

As Cincinnati’s Original Craft Beer, Christian Moerlein offers a fine line up of lagers and ales much like they did in the pre-prohibition era.  In 1841, Bavarian immigrant, Christian Moerlein, settled in Cincinnati’s Over-the-Rhine (OTR) brewery district, opening up the original brewery in 1853. Cincinnati Beer Baron, Greg Hardman, purchased Christian Moerlein in 2004. In 2010, the Christian Moerlein Brewery and Malt House opened it’s doors in the heart of OTR at the site of the original John Kaufmann Brewing Co.. Join the team Wednesday-Sunday at The CMB Malt House for a locally crafted favorite, a bite to eat, special events, and more! Connect with them on Facebook, Twitter, and Instragram. Prost!﻿<br><br>

**Comment by klcodanr** [comment]
Added in d277ec2887c93ba26874beb9b8b6c3c2c7e0354c
