### ISSUE TITLE
Update _people/alan-audette.html by Alan Audette on 10/18/2016

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#89]
---

date: 2016-10-18T13:16:02.503Z
title: Alan Audette
image: 'http://i.imgur.com/ZC7RFpM.jpg'
links: []
companies: []
projects: []
groups: []
author: Alan Audette
authorEmail: alan.audette@gmail.com
layout: profile
created: 2016-09-16T00:00:00.000Z

---

<p>CTO at AscendSMS. Co-founder and CTO at Springzy.</p>

**Comment by klcodanr** [comment]
Fixed in 50bac41842a44d48a981cf5f8df958ea13fdbcee
