### ISSUE TITLE
Update _people/frank-roberts.html by Frank Roberts on 11/4/2016

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#90]
---
date: 2016-11-04T10:29:01.120Z
title: Frank Roberts
image: 'http://i.imgur.com/2SWe3Y6.png'
links:
  - 'http://www.mojjari.com/software-outsourcing/'
companies: []
projects: []
groups: []
author: Frank Roberts
authorEmail: hello@mojjari.com
layout: profile
created: 2016-11-04T10:29:01.123Z

---

President at software development company Mojjari

**Comment by klcodanr** [comment]
Rejecting due to lack of credible response.
