### ISSUE TITLE
Update _events/startup-weekend-cincinnati-.html by Dan Klco on 11/14/2016

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#91]
---
date: 2016-11-14T17:43:14.164Z
title: 'Startup Weekend Cincinnati '
location: '1311 Vine Street  Cincinnati, OH 45202'
group: ''
startDate: '2016-11-18T18:30'
endDate: '2016-11-20T21:00'
displayTime: 'true'
image: 'http://i.imgur.com/lYTOkaW.jpg'
links:
  - 'http://www.up.co/communities/usa/cincinnati/startup-weekend'
author: Dan Klco
authorEmail: daniel.klco@gmail.com
created: 2016-11-14T17:43:14.166Z
layout: event

---

<p>Startup Weekend is a 54 hour event that brings together Cincinnati designers, developers, entrepreneurs, and experts from all domains to do amazing things.</p><p>All Startup Weekend events follow the same basic model: anyone is welcome to pitch their startup idea and receive feedback from their peers. Teams form around the top ideas (as determined by popular vote) and embark on a three-day frenzy of business model creation, coding, designing, and market validation. The weekend culminates with presentations in front of local entrepreneurial leaders with another opportunity for critical feedback!﻿</p>

**Comment by klcodanr** [comment]
Fixed in 02eaff043a59ad52f6fb602dbdd73994f5ce70cc
