### ISSUE TITLE
Update _companies/finola-jewelry.html by Veronica Bucher on 1/9/2018

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#94]
---
date: 2018-01-09T19:21:51.209Z
title: Finola Jewelry
industry: /companies/retail/
location: 'Cincinnati, OH'
image: ''
images: []
links:
  - 'https://fino.la/shop'
tags:
  - handmade jewelry
  - boho jewelry
  - handmade bohemian jewelry
  - tassel jewelry
  - 'bohemian jewelry '
  - lifestyle brand
author: Veronica Bucher
authorEmail: veronica@fino.la
created: 2018-01-09T19:21:51.211Z
layout: company

---

Handcrafted
  earrings, bracelets and necklaces made with hypoallergenic and ethically
  sourced materials. Made locally in Cincinnati, OH. Gemstones and fine materials. Shop dozens of bohemian
  wedding jewelry today.

**Comment by klcodanr** [comment]
Added in a83944cdf8400f594a3ec3c0e6ab285055bb2cb0
