### ISSUE TITLE
Update _companies/fnctn.html by Brice Lucas on 1/9/2018

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#95]
---
date: 2018-01-09T19:24:41.065Z
title: FNCTN
industry: /companies/tech/
location: 'Cincinnati, OH'
image: ''
images: []
links:
  - 'http://fnctn.com'
tags:
  - 'Custom Wordpress Development '
  - 'Online Marketing Strategy '
  - SEO
  - 'Paid Media '
  - " PPC \_"
  - 'CRM '
  - 'Radio '
  - 'Get Traffic '
  - 'Product development '
  - intellectual property
author: Brice Lucas
authorEmail: veronica@fnctn.com
created: 2018-01-09T19:24:41.066Z
layout: company

---

Technology, Marketing, and Business Consulting for Startups and Investors.&nbsp; ﻿Drive traffic to
  your website or business using FNCTN online marketing services.  With over 20 years of REAL experience
  working with fortune 100 companies, our data driven approach is transparent
  and effective. &nbsp;

**Comment by klcodanr** [comment]
Created in ce5ee9b
