### ISSUE TITLE
Update _people/sam-schutte.html by Sam Schutte on 1/22/2018

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#96]
---
date: 2018-01-22T22:05:58.894Z
title: Sam Schutte
image: 'https://i.imgur.com/ipJCUnz.jpg'
links:
  - 'http://unstoppablesoftware.com'
companies:
  - /companies/unstoppable-software/
projects: []
groups: []
author: Sam Schutte
authorEmail: sschutte@unstoppablesoftware.com
layout: profile
created: 2016-09-16T00:00:00.000Z

---

<p>Founder of Unstoppable Software, Inc. (@UnstoppableSW) Entrepreneur, C# Developer, Dad</p>

**Comment by klcodanr** [comment]
Updated in 3d179c63d1dbc9052ea4b846c8526e7a78c5a3e0
